### ISSUE TITLE
Error installing with npm

### ISSUE THREAD

**Issue by andrenatal** [tamarahills/metrics_controller#118]
Hi, I got this error trying to install with npm:

mozillas-mbp-8:vaani.client anatal$ npm install cd-metrics 
/Users/anatal/projects/mozilla/vaani-iot/vaani.client
`-- cd-metrics@0.0.5 
  +-- https@1.0.0 
`-- https-browserify@0.0.1 

npm WARN EJSONPARSE Failed to parse json
npm WARN EJSONPARSE No value found for key cd-metrics at 27:3
npm WARN EJSONPARSE   }
npm WARN EJSONPARSE   ^
npm WARN EPACKAGEJSON vaani.client No description
npm WARN EPACKAGEJSON vaani.client No repository field.
npm WARN EPACKAGEJSON vaani.client No README data
npm WARN EPACKAGEJSON vaani.client No license field.

**Comment by russnicoletti** [comment]
These warnings were resolved by adding the cd-metrics module to the vaani client package.json:

10:30 AM <andrenatal> russn: the npm install inside package.json did work!
10:31 AM <andrenatal> russn: I mean, npm install with the module set inside package.json
