### ISSUE TITLE
Encrypt the payload of the crash ping

### ISSUE THREAD

**Issue by tamarahills** [tamarahills/metrics_controller#7]

**Comment by tamarahills** [comment]
Right now, we need to convert the payload to a Vec<u8> to be able to convert it.  Currently, the body is in static str format.  It needs to be in that format to be sent.

**Comment by russnicoletti** [comment]
Done: 
    https://github.com/tamarahills/metrics_controller/commit/274b6389899b06390b9bebd70a694feb7fbe9b54
